# Generated by Django 3.0.7 on 2020-06-09 16:29

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comorbidite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomAntecedent', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomHopital', models.CharField(max_length=90)),
            ],
            options={
                'verbose_name': 'Hopital',
                'verbose_name_plural': 'Hopitaux',
            },
        ),
        migrations.CreateModel(
            name='Medicaments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomMedicament', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Medicament',
                'verbose_name_plural': 'Medicaments',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateDeNaissance', models.DateField()),
                ('Sexe', models.CharField(choices=[('HOMME', 'HOMME'), ('FEMME', 'FEMME')], max_length=10)),
                ('Statutmatrimonial', models.CharField(choices=[('Célibataire', 'Célibataire'), ('Marié', 'Marié'), ('Divorcé', 'Divorcé'), ('Veuf', 'Veuf'), ('Nonprécisée', 'Nonprécisée')], max_length=50)),
                ('NombreEnfants', models.IntegerField(default=0)),
                ('RevenumMensuel', models.CharField(choices=[('<2500 DH', '<2500 DH'), ('[2500 et 5000 DH[', '[2500 et 5000 DH['), ('[5000 et 10000 DH[ ', '[5000 et 10000 DH['), ('≥10000 DH ', '≥10000 DH '), ('Ne sait pas', 'Ne sait pas')], max_length=40)),
                ('NiveauEtude', models.CharField(choices=[('Primaire', 'Primaire'), ('Collège', 'Collège'), ('Bac +1 ou +2 ', 'Bac +1 ou +2'), ('Bac +3 ou +4', 'Bac +3 ou +4'), ('Bac +5 et plus', 'Bac +5 et plus'), ('Non scolarisé', 'Non scolarisé'), ('Ecole coranique', 'Ecole coranique')], max_length=40)),
                ('Activite', models.CharField(choices=[('élève', 'élève'), ('étudiant ou en formation ', 'étudiant ou en formation'), ('Actif', 'Actif'), ('Retraité', 'Retraité'), ("Chômeur (ou à la recherche d'un emploi)", "Chômeur (ou à la recherche d'un emploi)"), ('Femme au foyer', ' Femme au foyer'), ('Autre, préciser', 'Autre, préciser')], default='élève', max_length=100)),
                ('AutreActivite', models.CharField(blank=True, max_length=100)),
                ('Quartier', models.CharField(max_length=50)),
                ('Ville', models.CharField(max_length=40)),
                ('MilieuDeResidence', models.CharField(choices=[('Urbain', 'Urbain'), ('Rural', 'Rural')], max_length=10)),
                ('Poids', models.FloatField()),
                ('Taille', models.FloatField()),
                ('VaccinationBCG', models.BooleanField()),
                ('TabagismeActif', models.CharField(choices=[('Jamais fumé ', 'Jamais fumé '), ('Fumeur', 'Fumeur'), ('Ex-fumeur', 'Ex-fumeur')], max_length=30)),
                ('DureeDeConsommation', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='utilisateurDoctor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='utilisateurPatient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ZoneExposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expose', models.BooleanField()),
                ('Zone', models.CharField(blank=True, max_length=40)),
                ('DateExposition', models.DateField(blank=True)),
                ('Patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='UtilisationDesMedicaments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DureeUtilisation', models.IntegerField(blank=True)),
                ('AutreMedicaments', models.CharField(blank=True, max_length=90)),
                ('Medicament', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Medicaments')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='StatutClinique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomSymptome', multiselectfield.db.fields.MultiSelectField(choices=[('Fièvre', 'Fièvre'), ('Toux sèche', 'Toux sèche'), ('Essoufflement', 'Essoufflement'), ('Dyspnée', 'Dyspnée'), ('Douleurs musculaires', 'Douleurs musculaires'), ('Céphalées', 'Céphalées'), ('Fatigue', 'Fatigue'), ('Maux de gorge', 'Maux de gorge'), ('Pharyngite', 'Pharyngite'), ('Rhinorrhée', 'Rhinorrhée'), ('Douleur thoracique', 'Douleur thoracique'), ('Diarrhées', 'Diarrhées'), ('Nausée', 'Nausée'), ('Vomissements', 'Vomissements'), ('Symptomatologie', 'Symptomatologie'), ('psychiatrique', 'psychiatrique'), ('Autres Symptomes', 'Autres Symptomes')], max_length=210)),
                ('AutresSymptomes', models.CharField(blank=True, max_length=80)),
                ('ConclusionExamenClinique', models.CharField(max_length=90)),
                ('ConclusionExamenRadiologique', models.CharField(choices=[('Normale', 'Normale'), ('Verre dépoli', ' Verre dépoli'), ('Autres Lesions', 'Autres Lesions')], max_length=40)),
                ('AutresLesions', models.CharField(blank=True, max_length=80)),
                ('ClassificationSymptomatologique', models.CharField(choices=[('Asymptomatique', 'Asymptomatique'), ('Symptomatologie clinique de l’infection respiratoire haute (rhinite, pharyngite …)', 'Symptomatologie clinique de l’infection respiratoire haute (rhinite, pharyngite …)'), ('Symptomatologie clinique de l’infection respiratoire basse (symptômes de pneumonie ou de bronchite…)', 'Symptomatologie clinique de l’infection respiratoire basse (symptômes de pneumonie ou de bronchite…)')], max_length=100)),
                ('Patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.utilisateurPatient'),
        ),
        migrations.CreateModel(
            name='NEWS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.FloatField()),
                ('FréquenceRespiratoire', models.FloatField()),
                ('ToutSupplémentOxygène', models.FloatField()),
                ('SaturationOxygène', models.FloatField()),
                ('TA_Systolique', models.FloatField()),
                ('FréquenceCardiaque', models.FloatField()),
                ('Température', models.FloatField()),
                ('NiveauDeConscience', models.FloatField()),
                ('Patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='HistoireMaladiePersonnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HistoireMaladie', models.CharField(choices=[('Premiers symptômes', 'Premiers symptômes'), ('La 1ère consultation', 'La 1ère consultation'), ('La 1ère hospitalisation', 'La 1ère hospitalisation'), ('Premier diagnostic', 'Premier diagnostic'), ('Début de traitement ', 'Début de traitement ')], max_length=40)),
                ('Date', models.DateField()),
                ('Specification', models.CharField(max_length=80)),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Enceinte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grossesse', models.BooleanField(blank=True)),
                ('NbSemaineamenorrhee', models.IntegerField(blank=True)),
                ('Patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Hopital')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.utilisateurDoctor')),
            ],
        ),
        migrations.CreateModel(
            name='DevenirDuPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Etat', models.CharField(choices=[('Hospitalisation encours', 'Hospitalisation encours'), ('Sortie domicile', 'Sortie domicile'), ('Transfert', 'Transfert'), ('Décès', 'Décès')], max_length=90)),
                ('Patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='ContactAvecUnCas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ContactConfirme', models.BooleanField()),
                ('ContactPersonne', models.CharField(blank=True, choices=[('membre de famille', 'membre de famille'), ('Ami', 'Ami'), ('Collègue de travail', 'Collègue de travail'), ('Autre, préciser', 'Autre, préciser')], max_length=40)),
                ('AutreContact', models.CharField(blank=True, max_length=40)),
                ('SourceInconnue', models.BooleanField()),
                ('Patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='ComorbiditePersonnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgeAuDiagnostic', models.IntegerField(blank=True)),
                ('PriseDeTraitement', models.BooleanField(blank=True)),
                ('AutresMaladies', models.CharField(blank=True, max_length=90)),
                ('Comorbidite', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.Comorbidite')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Patient')),
            ],
        ),
    ]
