# Generated by Django 3.0.3 on 2020-05-27 01:47

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200527_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statutclinique',
            name='NomSymptome',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Fièvre', 'Fièvre'), ('Toux sèche', 'Toux sèche'), ('Essoufflement', 'Essoufflement'), ('Dyspnée', 'Dyspnée'), ('Douleurs musculaires', 'Douleurs musculaires'), ('Céphalées', 'Céphalées'), ('Fatigue', 'Fatigue'), ('Maux de gorge', 'Maux de gorge'), ('Pharyngite', 'Pharyngite'), ('Rhinorrhée', 'Rhinorrhée'), ('Douleur thoracique', 'Douleur thoracique'), ('Diarrhées', 'Diarrhées'), ('Nausée', 'Nausée'), ('Vomissements', 'Vomissements'), ('Symptomatologie', 'Symptomatologie'), ('psychiatrique', 'psychiatrique'), ('Autres, précisez', 'Autres, précisez')], max_length=210),
        ),
    ]
